// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.3
//   protoc               v5.27.3
// source: src/common/proto/sample_service.proto

/* eslint-disable */
import { Metadata } from '@grpc/grpc-js';
import { Observable } from 'rxjs';

export const protobufPackage = 'sampleservice';

export interface GetHelloRequest {}

export interface GetHelloResponse {
  message: string;
}

export interface AddNameRequest {
  name: string;
}

export interface AddNameResponse {
  message: string;
}

export interface PrintNamesRequest {
  size: number;
  nameFilter: string;
}

export interface PrintNamesResponse {
  names: string[];
}

export interface UploadFileRequest {
  fileName: string;
}

export interface UploadFileResponse {
  message: string;
}

export const SAMPLESERVICE_PACKAGE_NAME = 'sampleservice';

export interface SampleServiceClient {
  getHello(
    request: GetHelloRequest,
    metadata?: Metadata,
  ): Observable<GetHelloResponse>;

  addName(
    request: AddNameRequest,
    metadata?: Metadata,
  ): Observable<AddNameResponse>;

  printNames(
    request: PrintNamesRequest,
    metadata?: Metadata,
  ): Observable<PrintNamesResponse>;

  uploadFile(
    request: Observable<UploadFileRequest>,
    metadata?: Metadata,
  ): Observable<UploadFileResponse>;
}

export const SAMPLE_SERVICE_NAME = 'SampleService';
